### ISSUE TITLE
@candyskull920 replying to 

### ISSUE THREAD

**Issue by wmfadel** [mohamed0fadel/Crypto-Market#2]
@candyskull920 Sorry for not replying any sooner i really was busy
i would love to see your work if you are still interested

**Comment by candyskull920** [comment]
Hi @mohamed0fadel 
Of course there is no problem, I would like you to give me the excato name of the project and what exactly it is so that the logo is as accurate as possible.

Good day
Skull C.

**Comment by wmfadel** [comment]
@candyskull920 
The project name is Crypto Market and it was just a practice for me and the content was randomly selected. it just fetches data from api and displays then stores this data in local database to display for the user when he is offline.

**Comment by candyskull920** [comment]
@mohamed0fadel 
Soon I will be uploading my proposal.

Good day 
Skull C,.
